name: Selenium Functional Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  functional-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Download Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium Test
        run: python test_busqueda.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots
